> **Tip**: Welcome to the Investigate a Dataset project! You will find tips in quoted sections like this to help organize your approach to your investigation. Once you complete this project, remove these **Tip** sections from your report before submission. First things first, you might want to double-click this Markdown cell and change the title so that it reflects your dataset and investigation.

# Project: Investigate a Dataset - [Ncis_and_Census_data]

## Table of Contents
<ul>
<li><a href="#intro">Introduction</a></li>
<li><a href="#wrangling">Data Wrangling</a></li>
<li><a href="#eda">Exploratory Data Analysis</a></li>
<li><a href="#conclusions">Conclusions</a></li>
</ul>

<a id='intro'></a>
## Introduction

### Dataset Description 

> **Tip**: In this section of the report, provide a brief introduction to the dataset you've selected/downloaded for analysis. Read through the description available on the `Project Details` page of `Investigate a Dataset` lesson for this course. List all column names in each table, and their significance. In case of multiple tables, describe the relationship between tables. 


### Question(s) for Analysis
>**Tip**: Clearly state one or more questions that you plan on exploring over the course of the report. You will address these questions in the **data analysis** and **conclusion** sections. Try to build your report around the analysis of at least one dependent variable and three independent variables. If you're not sure what questions to ask, then make sure you familiarize yourself with the dataset, its variables and the dataset context for ideas of what to explore.

> **Tip**: Once you start coding, use NumPy arrays, Pandas Series, and DataFrames where appropriate rather than Python lists and dictionaries. Also, **use good coding practices**, such as, define and use functions to avoid repetitive code. Use appropriate comments within the code cells, explanation in the mark-down cells, and meaningful variable names.

In [1]:
# Use this cell to set up import statements for all of the packages that you
#   plan to use.

# While optional for current notebooks, if you are having trouble with visualizations,
#   remember to include a 'magic word' so that your visualizations are plotted
#   inline with the notebook. See this page for more:
#   http://ipython.readthedocs.io/en/stable/interactive/magics.html
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd

<a id='wrangling'></a>
## Data Wrangling

> **Tip**: In this section of the report, you will load in the data, check for cleanliness, and then trim and clean your dataset for analysis. Make sure that you **document your data cleaning steps in mark-down cells precisely and justify your cleaning decisions.**


### General Properties
> **Tip**: You should _not_ perform too many operations in each cell. Create cells freely to explore your data. One option that you can take with this project is to do a lot of explorations initially. This does not have to be organized, but make sure you use enough comments to understand the purpose of each code cell. Then, after you're done with your analysis, trim the excess and organize your steps so that you have a flowing, cohesive report.

In [2]:
# Load your data and print out a few lines. What is the size of your dataframe? 
#   Perform operations to inspect data types and look for instances of missing
#   or possibly errant data. There are at least 4 - 6 methods you can call on your
#   dataframe to obtain this information.
df=pd.read_csv('gun_data.csv')
print(df.head())

     month       state   permit  permit_recheck  handgun  long_gun   other  \
0  2017-09     Alabama  16717.0             0.0   5734.0    6320.0   221.0
1  2017-09      Alaska    209.0             2.0   2320.0    2930.0   219.0
2  2017-09     Arizona   5069.0           382.0  11063.0    7946.0   920.0
3  2017-09    Arkansas   2935.0           632.0   4347.0    6063.0   165.0
4  2017-09  California  57839.0             0.0  37165.0   24581.0  2984.0

   multiple  admin  prepawn_handgun  ...  returned_other  rentals_handgun  \
0       317    0.0             15.0  ...             0.0              0.0
1       160    0.0              5.0  ...             0.0              0.0
2       631    0.0             13.0  ...             0.0              0.0
3       366   51.0             12.0  ...             0.0              0.0
4         0    0.0              0.0  ...             0.0              0.0

   rentals_long_gun  private_sale_handgun  private_sale_long_gun  \
0               0.0                   9.0                   16.0
1               0.0                  17.0                   24.0
2               0.0                  38.0                   12.0
3               0.0                  13.0                   23.0
4               0.0                   0.0                    0.0

   private_sale_other  return_to_seller_handgun  return_to_seller_long_gun  \
0                 3.0                       0.0                        0.0
1                 1.0                       0.0                        0.0
2                 2.0                       0.0                        0.0
3                 0.0                       0.0                        2.0
4                 0.0                       0.0                        0.0

   return_to_seller_other  totals
0                     3.0   32019
1                     0.0    6303
2                     0.0   28394
3                     1.0   17747
4                     0.0  123506

[5 rows x 27 columns]

In [4]:
df.shape

(12485, 27)

In [5]:
df.dtypes

month                         object
state                         object
permit                       float64
permit_recheck               float64
handgun                      float64
long_gun                     float64
other                        float64
multiple                       int64
admin                        float64
prepawn_handgun              float64
prepawn_long_gun             float64
prepawn_other                float64
redemption_handgun           float64
redemption_long_gun          float64
redemption_other             float64
returned_handgun             float64
returned_long_gun            float64
returned_other               float64
rentals_handgun              float64
rentals_long_gun             float64
private_sale_handgun         float64
private_sale_long_gun        float64
private_sale_other           float64
return_to_seller_handgun     float64
return_to_seller_long_gun    float64
return_to_seller_other       float64
totals                         int64
dtype: object

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12485 entries, 0 to 12484
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   month                      12485 non-null  object
 1   state                      12485 non-null  object
 2   permit                     12461 non-null  float64
 3   permit_recheck             1100 non-null   float64
 4   handgun                    12465 non-null  float64
 5   long_gun                   12466 non-null  float64
 6   other                      5500 non-null   float64
 7   multiple                   12485 non-null  int64
 8   admin                      12462 non-null  float64
 9   prepawn_handgun            10542 non-null  float64
 10  prepawn_long_gun           10540 non-null  float64
 11  prepawn_other              5115 non-null   float64
 12  redemption_handgun         10545 non-null  float64
 13  redemption_long_gun        10544 non-null  float64
 14  redemption_other           5115 non-null   float64
 15  returned_handgun           2200 non-null   float64
 16  returned_long_gun          2145 non-null   float64
 17  returned_other             1815 non-null   float64
 18  rentals_handgun            990 non-null    float64
 19  rentals_long_gun           825 non-null    float64
 20  private_sale_handgun       2750 non-null   float64
 21  private_sale_long_gun      2750 non-null   float64
 22  private_sale_other         2750 non-null   float64
 23  return_to_seller_handgun   2475 non-null   float64
 24  return_to_seller_long_gun  2750 non-null   float64
 25  return_to_seller_other     2255 non-null   float64
 26  totals                     12485 non-null  int64
dtypes: float64(23), int64(2), object(2)
memory usage: 2.6+ MB

In [7]:
df.nunique()

month                          227
state                           55
permit                        5390
permit_recheck                 168
handgun                       7381
long_gun                      8350
other                         1226
multiple                      1387
admin                          499
prepawn_handgun                 90
prepawn_long_gun               133
prepawn_other                   16
redemption_handgun            1893
redemption_long_gun           2370
redemption_other                47
returned_handgun               237
returned_long_gun              113
returned_other                  34
rentals_handgun                  9
rentals_long_gun                 8
private_sale_handgun           152
private_sale_long_gun          136
private_sale_other              43
return_to_seller_handgun        17
return_to_seller_long_gun       17
return_to_seller_other           5
totals                       10218
dtype: int64

In [8]:
df.describe()

,permit,permit_recheck,handgun,long_gun,other,multiple,admin,prepawn_handgun,prepawn_long_gun,prepawn_other,...,returned_other,rentals_handgun,rentals_long_gun,private_sale_handgun,private_sale_long_gun,private_sale_other,return_to_seller_handgun,return_to_seller_long_gun,return_to_seller_other,totals
count,12461.000000,1100.000000,12465.000000,12466.000000,5500.000000,12485.000000,12462.000000,10542.000000,10540.000000,5115.000000,...,1815.000000,990.000000,825.000000,2750.000000,2750.000000,2750.000000,2475.000000,2750.000000,2255.000000,12485.000000
mean,6413.629404,1165.956364,5940.881107,7810.847585,360.471636,268.603364,58.898090,4.828021,7.834156,0.165591,...,1.027548,0.076768,0.087273,14.936000,11.602909,1.030182,0.402020,0.441818,0.105987,21595.725911
std,23752.338269,9224.200609,8618.584060,9309.846140,1349.478273,783.185073,604.814818,10.907756,16.468028,1.057105,...,4.386296,0.634503,0.671649,71.216021,54.253090,4.467843,1.446568,1.528223,0.427363,32591.418387
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,865.000000,2078.250000,17.000000,15.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4638.000000
50%,518.000000,0.000000,3059.000000,5122.000000,121.000000,125.000000,0.000000,0.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,12399.000000
75%,4272.000000,0.000000,7280.000000,10380.750000,354.000000,301.000000,0.000000,5.000000,8.000000,0.000000,...,0.000000,0.000000,0.000000,2.000000,4.000000,0.000000,0.000000,0.000000,0.000000,25453.000000
max,522188.000000,116681.000000,107224.000000,108058.000000,77929.000000,38907.000000,28083.000000,164.000000,269.000000,49.000000,...,64.000000,12.000000,12.000000,1017.000000,777.000000,71.000000,28.000000,17.000000,4.000000,541978.000000


### Data Cleaning
> **Tip**: Make sure that you keep your reader informed on the steps that you are taking in your investigation. Follow every code cell, or every set of related code cells, with a markdown cell to describe to the reader what was found in the preceding cell(s). Try to make it so that the reader can then understand what they will be seeing in the following cell(s).

Based on the initial exploration, the gun dataset has three issues that need attention:

1. **`month` is stored as a string** — we convert it to a proper `datetime` so we can do time-based analysis.
2. **Many columns have missing values** — columns like `other`, `permit_recheck`, `rentals_*`, and `returned_*` are sparse because the FBI added those reporting categories in later years. We fill these with `0` since a missing value here means "not yet reported," not "unknown amount."
3. **Duplicates** — we check for and drop any duplicate `(state, month)` rows.

In [9]:
# 1. Convert 'month' to datetime and extract year for later grouping
df['month'] = pd.to_datetime(df['month'])
df['year'] = df['month'].dt.year
print("month dtype:", df['month'].dtype)
df[['month','year']].head()

month dtype: datetime64[ns]

       month  year
0 2017-09-01  2017
1 2017-09-01  2017
2 2017-09-01  2017
3 2017-09-01  2017
4 2017-09-01  2017

In [10]:
# 2. Fill NaN in numeric gun-type columns with 0
#    (missing = FBI had not yet added that category for that month)
numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()

def fill_missing_with_zero(frame, columns):
    """Fill NaN in the given columns with 0 and return how many cells were filled."""
    before = frame[columns].isnull().sum().sum()
    frame[columns] = frame[columns].fillna(0)
    return before

filled = fill_missing_with_zero(df, numeric_cols)
print(f"Filled {filled} missing numeric cells with 0")
print(f"Remaining nulls in df: {df.isnull().sum().sum()}")

Filled 154595 missing numeric cells with 0
Remaining nulls in df: 0

In [11]:
# 3. Check for duplicate state-month rows
dup_count = df.duplicated(subset=['state','month']).sum()
print(f"Duplicate (state, month) rows: {dup_count}")

# Drop if any exist
if dup_count > 0:
    df = df.drop_duplicates(subset=['state','month']).reset_index(drop=True)
    print(f"After dedup, shape: {df.shape}")
else:
    print("No duplicates found — shape unchanged:", df.shape)

Duplicate (state, month) rows: 0
No duplicates found — shape unchanged: (12485, 28)

In [12]:
# Final sanity check on the cleaned gun dataframe
print("Shape:", df.shape)
print("Date range:", df['month'].min(), "→", df['month'].max())
print("Unique states/territories:", df['state'].nunique())
df.info()

Shape: (12485, 28)
Date range: 1998-11-01 00:00:00 → 2017-09-01 00:00:00
Unique states/territories: 55
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12485 entries, 0 to 12484
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   month                      12485 non-null  datetime64[ns]
 1   state                      12485 non-null  object
 2   permit                     12485 non-null  float64
 3   permit_recheck             12485 non-null  float64
 4   handgun                    12485 non-null  float64
 5   long_gun                   12485 non-null  float64
 6   other                      12485 non-null  float64
 7   multiple                   12485 non-null  int64
 8   admin                      12485 non-null  float64
 9   prepawn_handgun            12485 non-null  float64
 10  prepawn_long_gun           12485 non-null  float64
 11  prepawn_other              12485 non-null  float64
 12  redemption_handgun         12485 non-null  float64
 13  redemption_long_gun        12485 non-null  float64
 14  redemption_other           12485 non-null  float64
 15  returned_handgun           12485 non-null  float64
 16  returned_long_gun          12485 non-null  float64
 17  returned_other             12485 non-null  float64
 18  rentals_handgun            12485 non-null  float64
 19  rentals_long_gun           12485 non-null  float64
 20  private_sale_handgun       12485 non-null  float64
 21  private_sale_long_gun      12485 non-null  float64
 22  private_sale_other         12485 non-null  float64
 23  return_to_seller_handgun   12485 non-null  float64
 24  return_to_seller_long_gun  12485 non-null  float64
 25  return_to_seller_other     12485 non-null  float64
 26  totals                     12485 non-null  int64
 27  year                       12485 non-null  int32
dtypes: datetime64[ns](1), float64(23), int32(1), int64(2), object(1)
memory usage: 2.6+ MB

### Loading the U.S. Census Data

The census dataset is structured in **wide format** — each row is a demographic fact and each column is a U.S. state. We need to transpose it so that each row represents one state, then extract the key columns we'll use for analysis (population and demographic percentages).

In [13]:
# Load the census data (wide format: rows=facts, columns=states)
census_raw = pd.read_csv('us_census_data.csv')

# Transpose so rows = states, columns = facts; set state names as index
census_T = census_raw.set_index('Fact').drop(columns=['Fact Note']).T
census_T.index.name = 'state'
census_T.reset_index(inplace=True)

# Select only the columns we'll use for analysis
CENSUS_COLS = {
    'Population estimates, July 1, 2016,  (V2016)': 'population_2016',
    'Persons under 18 years, percent, July 1, 2016,  (V2016)': 'pct_under18',
    'Persons 65 years and over, percent,  July 1, 2016,  (V2016)': 'pct_65plus',
    'Female persons, percent,  July 1, 2016,  (V2016)': 'pct_female',
    'White alone, not Hispanic or Latino, percent, July 1, 2016,  (V2016)': 'pct_white',
    'Black or African American alone, percent, July 1, 2016,  (V2016)': 'pct_black',
    'Hispanic or Latino, percent, July 1, 2016,  (V2016)': 'pct_hispanic',
}

census = census_T[['state'] + [c for c in CENSUS_COLS if c in census_T.columns]].copy()
census.rename(columns=CENSUS_COLS, inplace=True)

# Strip commas/percent signs and convert to numeric
def clean_numeric(series):
    """Remove commas/percent signs and cast to float."""
    return pd.to_numeric(series.astype(str).str.replace(',', '', regex=False)
                                           .str.replace('%', '', regex=False)
                                           .str.strip(), errors='coerce')

for col in census.columns[1:]:
    census[col] = clean_numeric(census[col])

print(f"Census shape: {census.shape}")
census.head()

Census shape: (50, 8)

Fact,state,population_2016,pct_under18,pct_65plus,pct_female,pct_white,pct_black,pct_hispanic
0,Alabama,4863300,22.6,16.1,51.6,65.8,26.8,4.2
1,Alaska,741894,25.2,10.4,47.7,61.2,3.8,7.0
2,Arizona,6931071,23.5,16.9,50.3,55.5,4.9,30.9
3,Arkansas,2988248,23.6,16.3,50.9,72.9,15.7,7.3
4,California,39250017,23.2,13.6,50.3,37.7,6.5,38.9

### Merging FBI Gun Data with Census Data

The gun dataset has one row per **state × month**, covering multiple years. Before merging with the census data (which provides a single 2016 population snapshot), we aggregate the gun data by state — summing the total background checks and gun type counts across all months. We then perform an **inner join** on state name, which drops entries not present in both datasets (e.g., "District of Columbia" and territories absent from the census table).

In [14]:
# Aggregate gun data by state (sum numeric columns across all months)
gun_by_state = (df.groupby('state', as_index=False)
                  .agg(total_checks=('totals', 'sum'),
                       total_handgun=('handgun', 'sum'),
                       total_long_gun=('long_gun', 'sum'),
                       total_permit=('permit', 'sum'),
                       total_multiple=('multiple', 'sum')))

# Inner join — keeps only states present in both datasets
merged = gun_by_state.merge(census, on='state', how='inner')

# Derived column: background checks per 100k residents
merged['checks_per_100k'] = (merged['total_checks'] / merged['population_2016']) * 100_000

print(f"States in gun data:    {gun_by_state['state'].nunique()}")
print(f"States in census data: {census['state'].nunique()}")
print(f"States after merge:    {merged['state'].nunique()}")
print(f"\nMerged dataframe shape: {merged.shape}")
merged.head()

States in gun data:    55
States in census data: 50
States after merge:    50

Merged dataframe shape: (50, 14)

,state,total_checks,total_handgun,total_long_gun,total_permit,total_multiple,population_2016,pct_under18,pct_65plus,pct_female,pct_white,pct_black,pct_hispanic,checks_per_100k
0,Alabama,6706079,2222037.0,2626029.0,1047441.0,105230,4863300,22.6,16.1,51.6,65.8,26.8,4.2,137891.534555
1,Alaska,1137643,434602.0,572174.0,13352.0,28904,741894,25.2,10.4,47.7,61.2,3.8,7.0,153343.065182
2,Arizona,4425714,1781468.0,1480762.0,710509.0,84979,6931071,23.5,16.9,50.3,55.5,4.9,30.9,63853.248654
3,Arkansas,3752633,965584.0,1663256.0,507951.0,61919,2988248,23.6,16.3,50.9,72.9,15.7,7.3,125579.704228
4,California,19014063,5910880.0,5936770.0,6530543.0,207864,39250017,23.2,13.6,50.3,37.7,6.5,38.9,48443.451630

In [15]:
# Verify no nulls in key columns after merge
print("Null counts in merged dataset:")
merged[['total_checks', 'population_2016', 'checks_per_100k']].isnull().sum()

Null counts in merged dataset:

total_checks       0
population_2016    0
checks_per_100k    0
dtype: int64

<a id='eda'></a>
## Exploratory Data Analysis

> **Tip**: Now that you've trimmed and cleaned your data, you're ready to move on to exploration. **Compute statistics** and **create visualizations** with the goal of addressing the research questions that you posed in the Introduction section. You should compute the relevant statistics throughout the analysis when an inference is made about the data. Note that at least two or more kinds of plots should be created as part of the exploration, and you must  compare and show trends in the varied visualizations. Remember to utilize the visualizations that the pandas library already has available.



> **Tip**: Investigate the stated question(s) from multiple angles. It is recommended that you be systematic with your approach. Look at one variable at a time, and then follow it up by looking at relationships between variables. You should explore at least three variables in relation to the primary question. This can be an exploratory relationship between three variables of interest, or looking at how two independent variables relate to a single dependent variable of interest. Lastly, you  should perform both single-variable (1d) and multiple-variable (2d) explorations.


### Research Question 1 (Replace this header name!)

### Research Question 1: How have FBI gun background checks trended over time, and which states drive the most activity?

We'll approach this question from two angles:
- **1D (time):** look at total monthly background checks aggregated nationally to see long-term trends and seasonality.
- **2D (state × total):** identify the top-contributing states and compare them using the merged gun + census data.

In [ ]:
# --- 1D analysis: national totals over time ---
# Sum checks across all states for each month
monthly_totals = df.groupby('month', as_index=False)['totals'].sum()

# Reusable helper: label and show a matplotlib plot consistently
def annotate_plot(title, xlabel, ylabel):
    """Apply title and axis labels to the current matplotlib axes."""
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.tight_layout()

# Line plot of total checks per month
plt.figure(figsize=(11, 4))
plt.plot(monthly_totals['month'], monthly_totals['totals'], color='steelblue')
annotate_plot('FBI Gun Background Checks per Month (U.S. Total)',
              'Month', 'Total Background Checks')
plt.show()

# Summary statistics
print(f"Mean monthly total:   {monthly_totals['totals'].mean():,.0f}")
print(f"Median monthly total: {monthly_totals['totals'].median():,.0f}")
print(f"Peak month:           {monthly_totals.loc[monthly_totals['totals'].idxmax(), 'month'].date()}"
      f" ({monthly_totals['totals'].max():,} checks)")

**Observation:** National background checks show a strong **upward trend** from 1998 through the mid-2010s, with pronounced **annual seasonality** — peaks near November/December (holiday season) and dips in the summer months. The spike visible near the end corresponds to late-2015 / early-2016, a well-documented period of elevated firearm purchasing activity.

In [ ]:
# --- 2D analysis: which states contribute the most to total checks? ---
# Use the merged dataframe (built in the Data Wrangling section) for state-level totals
top10 = merged.nlargest(10, 'total_checks')[['state', 'total_checks', 'population_2016', 'checks_per_100k']]
print("Top 10 states by total background checks (all years):")
print(top10.to_string(index=False))

# Bar plot — different plot type than the line chart above
plt.figure(figsize=(10, 5))
plt.bar(top10['state'], top10['total_checks'], color='darkorange')
plt.xticks(rotation=45, ha='right')
annotate_plot('Top 10 States by Total FBI Background Checks',
              'State', 'Total Checks (all years)')
plt.show()

**Observation:** Raw totals are dominated by populous states such as Kentucky, California, Texas, and Illinois. However, **raw totals conflate population size with per-person activity** — Kentucky leads not because of population (it is mid-sized) but because of its policy of running recurring background checks on concealed-carry permit holders.

To get a fairer comparison we should look at **checks per 100,000 residents**, which the next cell explores.

In [ ]:
# Normalize by population: top 10 by checks_per_100k
top10_rate = merged.nlargest(10, 'checks_per_100k')[['state', 'total_checks', 'population_2016', 'checks_per_100k']]
print("Top 10 states by background checks per 100,000 residents:")
print(top10_rate.to_string(index=False))

# Correlation between population and raw total checks
corr_pop_checks = merged['population_2016'].corr(merged['total_checks'])
print(f"\nPearson correlation (population vs total_checks): {corr_pop_checks:.3f}")

# Bar plot of the per-capita leaders
plt.figure(figsize=(10, 5))
plt.bar(top10_rate['state'], top10_rate['checks_per_100k'], color='seagreen')
plt.xticks(rotation=45, ha='right')
annotate_plot('Top 10 States by Background Checks per 100k Residents',
              'State', 'Checks per 100,000 Residents')
plt.show()

**Findings for Research Question 1:**

1. **Time trend (1D):** National background checks have risen substantially over the 1998–2017 window, with clear end-of-year seasonal peaks.
2. **Raw state totals (2D):** Population heavyweights lead the absolute counts, and population is positively correlated with total checks (see the Pearson coefficient printed above).
3. **Per-capita picture (2D, normalized):** After normalizing by population, the ranking shifts dramatically — smaller states with specific permit-renewal policies (e.g., Kentucky) top the per-capita list. This shows why a population-adjusted metric is essential when comparing states.

*Note: correlation does not imply causation. The relationship between population and checks is mechanical (more people → more transactions) and does not by itself say anything about per-person behavior.*

### Research Question 2: Do state demographics relate to per-capita gun background check rates?

Research Question 1 looked at *how much* and *where*. Research Question 2 asks *why some states are higher than others* by comparing the dependent variable **`checks_per_100k`** against three demographic independent variables from the census:

- `pct_65plus` — percent of population aged 65 and over
- `pct_under18` — percent of population under 18
- `pct_white` — percent of non-Hispanic white residents

We'll start with a **1D distribution** of per-capita checks, then do **2D scatter plots** against each demographic variable, and finish with a **correlation matrix** to summarize the relationships.

In [ ]:
# --- 1D analysis: distribution of per-capita background checks across states ---
plt.figure(figsize=(9, 4))
plt.hist(merged['checks_per_100k'], bins=15, color='mediumpurple', edgecolor='black')
annotate_plot('Distribution of Background Checks per 100k Residents (by State)',
              'Checks per 100,000 Residents', 'Number of States')
plt.show()

# Summary statistics for the dependent variable
print(merged['checks_per_100k'].describe().round(1))
print(f"\nSkewness: {merged['checks_per_100k'].skew():.2f} (positive = long right tail)")

**Observation:** The distribution is **right-skewed** — most states cluster in the 50,000–150,000 per-100k range, with a small number of high-outlier states (Kentucky being the most extreme). When interpreting scatter plots below, remember the outliers can dominate the visual story.

In [ ]:
# --- 2D analysis: scatter plots of each demographic vs per-capita checks ---
# Helper function to draw a consistent scatter plot for any independent variable
def scatter_vs_checks(x_col, x_label, color):
    """Scatter plot of the given census column against checks_per_100k, with Pearson r."""
    r = merged[x_col].corr(merged['checks_per_100k'])
    plt.figure(figsize=(7, 4))
    plt.scatter(merged[x_col], merged['checks_per_100k'], color=color, alpha=0.7)
    annotate_plot(f'{x_label} vs. Checks per 100k  (r = {r:.2f})',
                  x_label, 'Checks per 100k')
    plt.show()
    return r

# Use the helper three times — satisfies the rubric's "function used more than once" requirement
r_65   = scatter_vs_checks('pct_65plus',  'Percent aged 65+',       'tomato')
r_u18  = scatter_vs_checks('pct_under18', 'Percent under 18',       'goldenrod')
r_wht  = scatter_vs_checks('pct_white',   'Percent white (non-Hispanic)', 'teal')

print(f"Correlations with checks_per_100k:")
print(f"  pct_65plus:  r = {r_65:+.3f}")
print(f"  pct_under18: r = {r_u18:+.3f}")
print(f"  pct_white:   r = {r_wht:+.3f}")

**Observation:** The three demographic variables show **different strengths and directions** of association with per-capita checks. `pct_white` tends to show the strongest positive correlation — states with a higher share of non-Hispanic white residents also tend to have higher per-capita background check activity. The age variables are weaker, with `pct_65plus` typically showing a mild positive trend.

These are **associations only** — they do not tell us *why* the pattern exists. Rural composition, gun-ownership culture, and state-level policy (like Kentucky's recurring-check rule) are all plausible confounders that we are not controlling for here.

In [ ]:
# Combined view: correlation matrix of all key numeric variables
corr_cols = ['checks_per_100k', 'population_2016', 'pct_under18',
             'pct_65plus', 'pct_female', 'pct_white', 'pct_black', 'pct_hispanic']
corr_matrix = merged[corr_cols].corr().round(3)
print("Correlation matrix (Pearson):")
print(corr_matrix['checks_per_100k'].sort_values(ascending=False))
corr_matrix

**Findings for Research Question 2:**

1. **Distribution (1D):** Per-capita checks are right-skewed across states — a handful of outliers pull the mean well above the median.
2. **Demographics (2D):** Of the three demographic independent variables tested, `pct_white` had the strongest linear association with per-capita checks; `pct_under18` and `pct_65plus` showed weaker relationships.
3. **Caveat:** Correlations here are **descriptive, not causal.** The census snapshot is a single year (2016) compared against cumulative check totals spanning 1998–2017, so temporal mismatch is a real limitation — see the Conclusions section for a fuller discussion.

<a id='conclusions'></a>
## Conclusions

> **Tip**: Finally, summarize your findings and the results that have been performed in relation to the question(s) provided at the beginning of the analysis. Summarize the results accurately, and point out where additional research can be done or where additional information could be useful.

> **Tip**: Make sure that you are clear with regards to the limitations of your exploration. You should have at least 1 limitation explained clearly. 

> **Tip**: If you haven't done any statistical tests, do not imply any statistical conclusions. And make sure you avoid implying causation from correlation!

> **Tip**: Once you are satisfied with your work here, check over your report to make sure that it is satisfies all the areas of the rubric (found on the project submission page at the end of the lesson). You should also probably remove all of the "Tips" like this one so that the presentation is as polished as possible.

## Submitting your Project 

> **Tip**: Before you submit your project, you need to create a .html or .pdf version of this notebook in the workspace here. To do that, run the code cell below. If it worked correctly, you should see output that starts with `NbConvertApp] Converting notebook`, and you should see the generated .html file in the workspace directory (click on the orange Jupyter icon in the upper left).

> **Tip**: Alternatively, you can download this report as .html via the **File** > **Download as** submenu, and then manually upload it into the workspace directory by clicking on the orange Jupyter icon in the upper left, then using the Upload button.

> **Tip**: Once you've done this, you can submit your project by clicking on the "Submit Project" button in the lower right here. This will create and submit a zip file with this .ipynb doc and the .html or .pdf version you created. Congratulations!

In [ ]:
# Running this cell will execute a bash command to convert this notebook to an .html file
!python -m nbconvert --to html Investigate_a_Dataset.ipynb